title:              Ky Nguyen
email:              nguyendaiky@gmail.com
description:        Welcome to my blog
author:             Ky Nguyen
baseurl:            ""
url:                "https://nguyendaikyy.github.io"

# Social Profiles
twitter_username:   nguyendaiky
github_username:   nguyendaiky
facebook_username:  nguyendaikyy
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
